# -*- coding: utf-8 -*-
"""Lab5_FINAL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TDJoqAHRJPAXsGDsfB53jAzsga9QU8Md
"""

import pandas as pd

from google.colab import files
uploaded = files.upload()

import os
os.listdir()

df = pd.read_csv("insurance.csv")
df.head()

df.info(), df.head()

import matplotlib.pyplot as plt
import seaborn as sns

sns.set_style("whitegrid")

fig, axes = plt.subplots(2, 3, figsize=(18, 12))
fig.suptitle("Matplotlib Visualizations", fontsize=16)

df['smoker'].value_counts().plot(kind='bar', color=['lightblue', 'salmon'], ax=axes[0, 0])
axes[0, 0].set_title("Count of Smokers vs. Non-Smokers")
axes[0, 0].set_ylabel("Count")

axes[0, 1].hist(df['bmi'], bins=20, color='purple', alpha=0.7)
axes[0, 1].set_title("BMI Distribution")
axes[0, 1].set_xlabel("BMI")
axes[0, 1].set_ylabel("Frequency")

axes[0, 2].scatter(df['bmi'], df['charges'], alpha=0.5, color='green')
axes[0, 2].set_title("BMI vs. Insurance Charges")
axes[0, 2].set_xlabel("BMI")
axes[0, 2].set_ylabel("Charges")

age_charges = df.groupby("age")["charges"].mean()
axes[1, 0].plot(age_charges.index, age_charges.values, marker='o', linestyle='-', color='blue')
axes[1, 0].set_title("Average Charges by Age")
axes[1, 0].set_xlabel("Age")
axes[1, 0].set_ylabel("Average Charges")

df['region'].value_counts().plot(kind='pie', autopct='%1.1f%%', colors=['#ff9999','#66b3ff','#99ff99','#ffcc99'], ax=axes[1, 1])
axes[1, 1].set_title("Region Distribution")
axes[1, 1].set_ylabel("")

plt.tight_layout(rect=[0, 0, 1, 0.96])
plt.show()

df_numeric = df.select_dtypes(include=['number'])

fig, axes = plt.subplots(2, 3, figsize=(18, 12))
fig.suptitle("Seaborn Visualizations", fontsize=16)

sns.barplot(x='smoker', y='charges', hue='smoker', data=df, palette=['lightblue', 'salmon'], dodge=False, ax=axes[0, 0])
axes[0, 0].set_title("Average Insurance Charges by Smoker Status")

sns.boxplot(x='sex', y='bmi', hue='sex', data=df, palette='coolwarm', dodge=False, ax=axes[0, 1])
axes[0, 1].set_title("BMI Distribution by Sex")

sns.scatterplot(x='bmi', y='charges', hue='smoker', data=df, alpha=0.7, ax=axes[0, 2])
axes[0, 2].set_title("BMI vs. Charges (Smokers vs. Non-Smokers)")

corr_matrix = df_numeric.corr()
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', fmt=".2f", ax=axes[1, 0])
axes[1, 0].set_title("Correlation Heatmap")

sns.violinplot(x='region', y='charges', data=df, palette='Set2', ax=axes[1, 1])
axes[1, 1].set_title("Distribution of Charges by Region")

plt.tight_layout(rect=[0, 0, 1, 0.96])
plt.show()